version: "3.9"
services:
  keycloak-postgres:
    image: postgres:15.2
    container_name: keycloak_postgres_service_test
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: pg_isready -d postgres
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          memory: 256M

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    container_name: keycloak
    command:
      - start --auto-build --db postgres --hostname-strict-https false --hostname-strict false --proxy edge --http-enabled true --import-realm --spi-user-profile-legacy-user-profile-read-only-attributes *_RES_ACCESS_MODE
    environment:
      KC_DB_URL: jdbc:postgresql://keycloak-postgres:5432/postgres
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KC_DB_SCHEMA: public
      KC_FEATURES: preview
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8282:8080"
    depends_on:
      keycloak-postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://0.0.0.0:8080/realms/master" ]
      start_period: 10s
      interval: 30s
      retries: 3
      timeout: 5s

  swagger-ui:
    image: swaggerapi/swagger-ui:v5.0.0
    ports:
      - "8080:8080"
    environment:
     # - BASE_URL= /swagger-ui
      - BASE_URL=/swagger-ui
      - URL=http://localhost:8090/v3/api-docs
      - OAUTH_CLIENT_ID=swagger-ui
      - OAUTH_CLIENT_SECRET=ZoistP5MrGPQdSBfC9kdmPJC1OEhqgCx
      - OAUTH_REALM=dev
      - OAUTH_SERVER_URL=http://45.141.103.134:8282/auth/
     # - OAUTH_SCOPES=read,write
      - OAUTH_APP_NAME= myapp
    #  - SWAGGER_JSON=/app/swagger.yml
    networks:
        - vesuvian-network
#    volumes:
#      - ./config:/app
networks:
  vesuvian-network:
    driver: bridge