server:
  port: 8090
  ssl:
    enabled: false # настройка для Spring что бы он использовал SSL


spring:
  application:
    name: security
  security:

    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: http://45.141.103.134:8282/realms/dev/protocol/openid-connect/certs # ссылка на сертификаты authserver для проверки целостности access token


keycloak:
  auth-server-url: http://45.141.103.134:8282/
  realm: dev
  resource: app-dev-client
  username: admin
  password: admin

clientURL: http://localhost:3000 # тестовый порт REACT