server:
  port: 8090
  ssl:
    enabled: false # настройка для Spring что бы он использовал SSL


spring:
  application:
    name: customer
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: http://45.141.103.134:8282/realms/dev/protocol/openid-connect/certs # ссылка на сертификаты authserver для проверки целостности access token


keycloak:
  realm: dev
  auth-server-url: http://45.141.103.134:8282/auth
  resource: swagger-ui
  credentials:
    secret: ZoistP5MrGPQdSBfC9kdmPJC1OEhqgCx

  authorization:
    auth-server-url: http://45.141.103.134:8282
    realm: dev
    resource: app-dev-client
    username: admin
    password: admin

clientURL: http://localhost:3000 # тестовый порт REACT

application:
  default:
    page: 10
    size: 10


springdoc:
  swagger-ui:
    oauth:
      client-id: swagger-ui
      app-name: swagger-ui
#    url: /swagger/v1/customers
#  api-docs:
#    path: /swagger/v1/customers


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
     defaultZone: http://eureka-server:8761/eureka/
     #defaultZone: http://localhost:8761/eureka/