server:
  port: 8090
  ssl:
    enabled: false # настройка для Spring что бы он использовал SSL


spring:
  application:
    name: customer
  config:
    import: optional:file:.env[.properties]
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: http://212.113.120.198:8282/realms/dev/protocol/openid-connect/certs # ссылка на сертификаты authserver для проверки целостности access token
  datasource:
    url: jdbc:postgresql://customer-postgres:5432/customers
#   url: jdbc:postgresql://localhost:5435/customers
    username: postgres
    password: ${CUSTOMER_POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
      show-sql: true


keycloak:
  realm: dev
  auth-server-url: http://212.113.120.198:8282/auth

  authorization:
    auth-server-url: http://212.113.120.198:8282
    realm: dev
    resource: app-dev-client
    username: admin
    password: ${KEYCLOAK_USER_ADMIN_PASSWORD}

clientURL: http://localhost:3000 # тестовый порт REACT

application:
  default:
    page: 10
    size: 10


springdoc:
  swagger-ui:
    oauth:
      client-id: swagger-ui
      app-name: swagger-ui
#    url: /swagger/v1/customers
#  api-docs:
#    path: /swagger/v1/customers


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
     defaultZone: http://eureka-server:8761/eureka/
     #defaultZone: http://localhost:8761/eureka/