openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'My API'
servers:
  - url: 'http://localhost:8090/api'

components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: http://45.141.103.134:8282/realms/dev/protocol/openid-connect/auth
          tokenUrl: http://45.141.103.134:8282/realms/dev/protocol/openid-connect/token
          scopes:
            read: grants read access
            write: grants write access

paths:
  /api/v1/customers:
    get:
      summary: 'API endpoint'
      responses:
        200:
          description: 'Successful response'
      security:
        - oauth2: [read]