server:
  port: 8095
  ssl:
    enabled: false # настройка для Spring что бы он использовал SSL


spring:
  application:
    name: imageService
  config:
    import: optional:file:.env[.properties]

yandex-cloud:
  bucket-name: vesuvian-images
  buckets:
    vesuvian-images:
      client:
        design-elements: client/design-elements/
