server:
  port: 8083

spring:
  application:
    name: api-gateway


  # Configuring API Gateway
  cloud:
    gateway:
      routes:
        - id: customer # добавляем микросервис customer
          uri: lb://CUSTOMER # берется из eureka server
          predicates:
            - Path=/** # позволяем использовать любые запросы по этому пути


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/