export const DARK_MODE_REDUCER = {
  DARK_MODE: 'DARK_MODE',
}

export const AUTHENTICATION_STATUS = {
  AUTH_STATUS: 'AUTH',
  AUTH_STATE: 'STATE',
}

export const CURRENT_CUSTOMER_DATA = {
  APPEND_DATA: 'APPEND_DATA',
  FETCH_DATA_ERROR: 'FETCH_DATA_ERROR'
}