name: Deploy customer to Docker

on:
  push:
    branches:
      - customer

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        working-directory: ./    # set working directory to project root
        run: mvn -B package --file pom.xml

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: server/security
          dockerfile: Dockerfile
          push: true
          tags: ghcr.io/mrdimenter/customer:latest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: install ssh keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

      - name: Deploy to remote
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
          docker pull ghcr.io/mrdimenter/customer:latest
          
          # Get the container id
          CONTAINER_ID=$(docker ps -aqf "name=customer")
  
          # Check if the container is running
          if [ "$CONTAINER_ID" ]; then
          docker stop $CONTAINER_ID
          docker rm -f  $CONTAINER_ID
          fi
          
          # Remove old Docker images with <none> tags
          docker rmi -f $(docker images -f "dangling=true" -q)
          docker run -d --name customer -p 8090:8090 ghcr.io/mrdimenter/customer:latest
          "
