name: Deploy customer to Docker

on:
  push:
    branches:
      - customer

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/vesuvian/customer-service:latest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Deploy to remote
        run: |
          ssh -o "StrictHostKeyChecking=no" ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
          docker pull ghcr.io/vesuvian/customer-service:latest
          docker stop customer-service
          docker rm customer-service
          docker run -d --name customer-service -p 8080:8080 ghcr.io/vesuvian/customer-service:latest
          "
        env:
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}