name: Deploy customer to Docker

on:
  push:
    branches:
      - customer

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        working-directory: ./    # set working directory to project root
        run: mvn -B package --file pom.xml

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: server/security
          dockerfile: Dockerfile
          push: true
          tags: ghcr.io/mrdimenter/customer:latest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Deploy to remote
        run: |
          ssh -o "StrictHostKeyChecking=no" ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
          docker pull ghcr.io/mrdimenter/customer:latest
          docker stop customer
          docker rm customer
          docker run -d --name customer -p 8080:8080 ghcr.io/vesuvian/customer:latest
          "
        env:
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}